apiVersion: webhookconfig.keptn.sh/v1beta1
kind: WebhookConfig
metadata:
  name: webhook-configuration
spec:
  webhooks:
    - type: sh.keptn.event.evaluation.finished
      requests:
        - url: https://webexapis.com/v1/webhooks/incoming/Y2lzY29zcGFyazovL3VzL1dFQkhPT0svNjU4YTgyYmMtOTBhMC00YTk0LTgzM2QtZmE1YjRjZDU0MzI3
          payload: >-
            {"markdown":"Evaluation for project {{.data.project}} ended.  Result: {{.data.result}}"}
          headers:
            - key: Content-Type
              value: application/json
          method: POST
      subscriptionID: d6195116-b6db-40cc-b4b1-95366d780831
      sendFinished: false
      sendStarted: false
