apiVersion: v2
actions:
  - name: "Run Neo"
    events:
      - name: "sh.keptn.event.test.triggered"
        jsonpath:
          property: "$.data.test.teststrategy"
          match: "performance"
    tasks:
      - name: "Run Neo tests"
        image: "cjmckenna/neojes:latest"